/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as MemoirRouteImport } from './routes/memoir'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembershipSuccessRouteImport } from './routes/membership.success'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as AdminVerifyRouteImport } from './routes/admin.verify'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionRouteImport } from './routes/admin.subscription'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as BooksSlugIndexRouteImport } from './routes/books.$slug.index'
import { Route as AdminNewsletterIndexRouteImport } from './routes/admin.newsletter.index'
import { Route as EventsCancelTokenRouteImport } from './routes/events.cancel.$token'
import { Route as EventsIdSuccessRouteImport } from './routes/events.$id.success'
import { Route as BooksSlugChapterSlugRouteImport } from './routes/books.$slug.$chapterSlug'
import { Route as AdminNewsletterNewRouteImport } from './routes/admin.newsletter.new'
import { Route as AdminNewsletterIdRouteImport } from './routes/admin.newsletter.$id'
import { Route as AdminEventsCreateRouteImport } from './routes/admin.events.create'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'
import { Route as AdminBooksCreateRouteImport } from './routes/admin.books.create'
import { Route as AdminBooksIdRouteImport } from './routes/admin.books.$id'
import { Route as AdminNewsletterIdPreviewRouteImport } from './routes/admin.newsletter.$id.preview'
import { Route as AdminNewsletterIdEditRouteImport } from './routes/admin.newsletter.$id.edit'
import { Route as AdminEventsIdRegistrationsRouteImport } from './routes/admin.events.$id.registrations'
import { Route as AdminBooksIdChaptersRouteImport } from './routes/admin.books.$id.chapters'
import { Route as AdminBooksIdChaptersNewRouteImport } from './routes/admin.books.$id.chapters.new'
import { Route as AdminBooksIdChaptersChapterIdEditRouteImport } from './routes/admin.books.$id.chapters.$chapterId.edit'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoirRoute = MemoirRouteImport.update({
  id: '/memoir',
  path: '/memoir',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipSuccessRoute = MembershipSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => MembershipRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionRoute = AdminSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)
const BooksSlugIndexRoute = BooksSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksSlugRoute,
} as any)
const AdminNewsletterIndexRoute = AdminNewsletterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNewsletterRoute,
} as any)
const EventsCancelTokenRoute = EventsCancelTokenRouteImport.update({
  id: '/cancel/$token',
  path: '/cancel/$token',
  getParentRoute: () => EventsRoute,
} as any)
const EventsIdSuccessRoute = EventsIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => EventsIdRoute,
} as any)
const BooksSlugChapterSlugRoute = BooksSlugChapterSlugRouteImport.update({
  id: '/$chapterSlug',
  path: '/$chapterSlug',
  getParentRoute: () => BooksSlugRoute,
} as any)
const AdminNewsletterNewRoute = AdminNewsletterNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNewsletterRoute,
} as any)
const AdminNewsletterIdRoute = AdminNewsletterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminNewsletterRoute,
} as any)
const AdminEventsCreateRoute = AdminEventsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminBooksCreateRoute = AdminBooksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminBooksRoute,
} as any)
const AdminBooksIdRoute = AdminBooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBooksRoute,
} as any)
const AdminNewsletterIdPreviewRoute =
  AdminNewsletterIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AdminNewsletterIdRoute,
  } as any)
const AdminNewsletterIdEditRoute = AdminNewsletterIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminNewsletterIdRoute,
} as any)
const AdminEventsIdRegistrationsRoute =
  AdminEventsIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AdminEventsIdRoute,
  } as any)
const AdminBooksIdChaptersRoute = AdminBooksIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AdminBooksIdRoute,
} as any)
const AdminBooksIdChaptersNewRoute = AdminBooksIdChaptersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBooksIdChaptersRoute,
} as any)
const AdminBooksIdChaptersChapterIdEditRoute =
  AdminBooksIdChaptersChapterIdEditRouteImport.update({
    id: '/$chapterId/edit',
    path: '/$chapterId/edit',
    getParentRoute: () => AdminBooksIdChaptersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/memoir': typeof MemoirRoute
  '/podcast': typeof PodcastRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/books': typeof AdminBooksRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscription': typeof AdminSubscriptionRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/membership/success': typeof MembershipSuccessRoute
  '/admin/books/$id': typeof AdminBooksIdRouteWithChildren
  '/admin/books/create': typeof AdminBooksCreateRoute
  '/admin/events/$id': typeof AdminEventsIdRouteWithChildren
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/newsletter/$id': typeof AdminNewsletterIdRouteWithChildren
  '/admin/newsletter/new': typeof AdminNewsletterNewRoute
  '/books/$slug/$chapterSlug': typeof BooksSlugChapterSlugRoute
  '/events/$id/success': typeof EventsIdSuccessRoute
  '/events/cancel/$token': typeof EventsCancelTokenRoute
  '/admin/newsletter/': typeof AdminNewsletterIndexRoute
  '/books/$slug/': typeof BooksSlugIndexRoute
  '/admin/books/$id/chapters': typeof AdminBooksIdChaptersRouteWithChildren
  '/admin/events/$id/registrations': typeof AdminEventsIdRegistrationsRoute
  '/admin/newsletter/$id/edit': typeof AdminNewsletterIdEditRoute
  '/admin/newsletter/$id/preview': typeof AdminNewsletterIdPreviewRoute
  '/admin/books/$id/chapters/new': typeof AdminBooksIdChaptersNewRoute
  '/admin/books/$id/chapters/$chapterId/edit': typeof AdminBooksIdChaptersChapterIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/memoir': typeof MemoirRoute
  '/podcast': typeof PodcastRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/books': typeof AdminBooksRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscription': typeof AdminSubscriptionRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/membership/success': typeof MembershipSuccessRoute
  '/admin/books/$id': typeof AdminBooksIdRouteWithChildren
  '/admin/books/create': typeof AdminBooksCreateRoute
  '/admin/events/$id': typeof AdminEventsIdRouteWithChildren
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/newsletter/$id': typeof AdminNewsletterIdRouteWithChildren
  '/admin/newsletter/new': typeof AdminNewsletterNewRoute
  '/books/$slug/$chapterSlug': typeof BooksSlugChapterSlugRoute
  '/events/$id/success': typeof EventsIdSuccessRoute
  '/events/cancel/$token': typeof EventsCancelTokenRoute
  '/admin/newsletter': typeof AdminNewsletterIndexRoute
  '/books/$slug': typeof BooksSlugIndexRoute
  '/admin/books/$id/chapters': typeof AdminBooksIdChaptersRouteWithChildren
  '/admin/events/$id/registrations': typeof AdminEventsIdRegistrationsRoute
  '/admin/newsletter/$id/edit': typeof AdminNewsletterIdEditRoute
  '/admin/newsletter/$id/preview': typeof AdminNewsletterIdPreviewRoute
  '/admin/books/$id/chapters/new': typeof AdminBooksIdChaptersNewRoute
  '/admin/books/$id/chapters/$chapterId/edit': typeof AdminBooksIdChaptersChapterIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/memoir': typeof MemoirRoute
  '/podcast': typeof PodcastRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/books': typeof AdminBooksRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscription': typeof AdminSubscriptionRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/books/$slug': typeof BooksSlugRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/membership/success': typeof MembershipSuccessRoute
  '/admin/books/$id': typeof AdminBooksIdRouteWithChildren
  '/admin/books/create': typeof AdminBooksCreateRoute
  '/admin/events/$id': typeof AdminEventsIdRouteWithChildren
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/newsletter/$id': typeof AdminNewsletterIdRouteWithChildren
  '/admin/newsletter/new': typeof AdminNewsletterNewRoute
  '/books/$slug/$chapterSlug': typeof BooksSlugChapterSlugRoute
  '/events/$id/success': typeof EventsIdSuccessRoute
  '/events/cancel/$token': typeof EventsCancelTokenRoute
  '/admin/newsletter/': typeof AdminNewsletterIndexRoute
  '/books/$slug/': typeof BooksSlugIndexRoute
  '/admin/books/$id/chapters': typeof AdminBooksIdChaptersRouteWithChildren
  '/admin/events/$id/registrations': typeof AdminEventsIdRegistrationsRoute
  '/admin/newsletter/$id/edit': typeof AdminNewsletterIdEditRoute
  '/admin/newsletter/$id/preview': typeof AdminNewsletterIdPreviewRoute
  '/admin/books/$id/chapters/new': typeof AdminBooksIdChaptersNewRoute
  '/admin/books/$id/chapters/$chapterId/edit': typeof AdminBooksIdChaptersChapterIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/memoir'
    | '/podcast'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/subscribe'
    | '/terms'
    | '/unsubscribe'
    | '/verify-otp'
    | '/admin/books'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/subscription'
    | '/admin/users'
    | '/admin/verify'
    | '/books/$slug'
    | '/events/$id'
    | '/membership/success'
    | '/admin/books/$id'
    | '/admin/books/create'
    | '/admin/events/$id'
    | '/admin/events/create'
    | '/admin/newsletter/$id'
    | '/admin/newsletter/new'
    | '/books/$slug/$chapterSlug'
    | '/events/$id/success'
    | '/events/cancel/$token'
    | '/admin/newsletter/'
    | '/books/$slug/'
    | '/admin/books/$id/chapters'
    | '/admin/events/$id/registrations'
    | '/admin/newsletter/$id/edit'
    | '/admin/newsletter/$id/preview'
    | '/admin/books/$id/chapters/new'
    | '/admin/books/$id/chapters/$chapterId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/memoir'
    | '/podcast'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/subscribe'
    | '/terms'
    | '/unsubscribe'
    | '/verify-otp'
    | '/admin/books'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/subscription'
    | '/admin/users'
    | '/admin/verify'
    | '/events/$id'
    | '/membership/success'
    | '/admin/books/$id'
    | '/admin/books/create'
    | '/admin/events/$id'
    | '/admin/events/create'
    | '/admin/newsletter/$id'
    | '/admin/newsletter/new'
    | '/books/$slug/$chapterSlug'
    | '/events/$id/success'
    | '/events/cancel/$token'
    | '/admin/newsletter'
    | '/books/$slug'
    | '/admin/books/$id/chapters'
    | '/admin/events/$id/registrations'
    | '/admin/newsletter/$id/edit'
    | '/admin/newsletter/$id/preview'
    | '/admin/books/$id/chapters/new'
    | '/admin/books/$id/chapters/$chapterId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/memoir'
    | '/podcast'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/subscribe'
    | '/terms'
    | '/unsubscribe'
    | '/verify-otp'
    | '/admin/books'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/subscription'
    | '/admin/users'
    | '/admin/verify'
    | '/books/$slug'
    | '/events/$id'
    | '/membership/success'
    | '/admin/books/$id'
    | '/admin/books/create'
    | '/admin/events/$id'
    | '/admin/events/create'
    | '/admin/newsletter/$id'
    | '/admin/newsletter/new'
    | '/books/$slug/$chapterSlug'
    | '/events/$id/success'
    | '/events/cancel/$token'
    | '/admin/newsletter/'
    | '/books/$slug/'
    | '/admin/books/$id/chapters'
    | '/admin/events/$id/registrations'
    | '/admin/newsletter/$id/edit'
    | '/admin/newsletter/$id/preview'
    | '/admin/books/$id/chapters/new'
    | '/admin/books/$id/chapters/$chapterId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRouteWithChildren
  MemoirRoute: typeof MemoirRoute
  PodcastRoute: typeof PodcastRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  BooksSlugRoute: typeof BooksSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoir': {
      id: '/memoir'
      path: '/memoir'
      fullPath: '/memoir'
      preLoaderRoute: typeof MemoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/success': {
      id: '/membership/success'
      path: '/success'
      fullPath: '/membership/success'
      preLoaderRoute: typeof MembershipSuccessRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscription': {
      id: '/admin/subscription'
      path: '/subscription'
      fullPath: '/admin/subscription'
      preLoaderRoute: typeof AdminSubscriptionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/books/$slug/': {
      id: '/books/$slug/'
      path: '/'
      fullPath: '/books/$slug/'
      preLoaderRoute: typeof BooksSlugIndexRouteImport
      parentRoute: typeof BooksSlugRoute
    }
    '/admin/newsletter/': {
      id: '/admin/newsletter/'
      path: '/'
      fullPath: '/admin/newsletter/'
      preLoaderRoute: typeof AdminNewsletterIndexRouteImport
      parentRoute: typeof AdminNewsletterRoute
    }
    '/events/cancel/$token': {
      id: '/events/cancel/$token'
      path: '/cancel/$token'
      fullPath: '/events/cancel/$token'
      preLoaderRoute: typeof EventsCancelTokenRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$id/success': {
      id: '/events/$id/success'
      path: '/success'
      fullPath: '/events/$id/success'
      preLoaderRoute: typeof EventsIdSuccessRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/books/$slug/$chapterSlug': {
      id: '/books/$slug/$chapterSlug'
      path: '/$chapterSlug'
      fullPath: '/books/$slug/$chapterSlug'
      preLoaderRoute: typeof BooksSlugChapterSlugRouteImport
      parentRoute: typeof BooksSlugRoute
    }
    '/admin/newsletter/new': {
      id: '/admin/newsletter/new'
      path: '/new'
      fullPath: '/admin/newsletter/new'
      preLoaderRoute: typeof AdminNewsletterNewRouteImport
      parentRoute: typeof AdminNewsletterRoute
    }
    '/admin/newsletter/$id': {
      id: '/admin/newsletter/$id'
      path: '/$id'
      fullPath: '/admin/newsletter/$id'
      preLoaderRoute: typeof AdminNewsletterIdRouteImport
      parentRoute: typeof AdminNewsletterRoute
    }
    '/admin/events/create': {
      id: '/admin/events/create'
      path: '/create'
      fullPath: '/admin/events/create'
      preLoaderRoute: typeof AdminEventsCreateRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/books/create': {
      id: '/admin/books/create'
      path: '/create'
      fullPath: '/admin/books/create'
      preLoaderRoute: typeof AdminBooksCreateRouteImport
      parentRoute: typeof AdminBooksRoute
    }
    '/admin/books/$id': {
      id: '/admin/books/$id'
      path: '/$id'
      fullPath: '/admin/books/$id'
      preLoaderRoute: typeof AdminBooksIdRouteImport
      parentRoute: typeof AdminBooksRoute
    }
    '/admin/newsletter/$id/preview': {
      id: '/admin/newsletter/$id/preview'
      path: '/preview'
      fullPath: '/admin/newsletter/$id/preview'
      preLoaderRoute: typeof AdminNewsletterIdPreviewRouteImport
      parentRoute: typeof AdminNewsletterIdRoute
    }
    '/admin/newsletter/$id/edit': {
      id: '/admin/newsletter/$id/edit'
      path: '/edit'
      fullPath: '/admin/newsletter/$id/edit'
      preLoaderRoute: typeof AdminNewsletterIdEditRouteImport
      parentRoute: typeof AdminNewsletterIdRoute
    }
    '/admin/events/$id/registrations': {
      id: '/admin/events/$id/registrations'
      path: '/registrations'
      fullPath: '/admin/events/$id/registrations'
      preLoaderRoute: typeof AdminEventsIdRegistrationsRouteImport
      parentRoute: typeof AdminEventsIdRoute
    }
    '/admin/books/$id/chapters': {
      id: '/admin/books/$id/chapters'
      path: '/chapters'
      fullPath: '/admin/books/$id/chapters'
      preLoaderRoute: typeof AdminBooksIdChaptersRouteImport
      parentRoute: typeof AdminBooksIdRoute
    }
    '/admin/books/$id/chapters/new': {
      id: '/admin/books/$id/chapters/new'
      path: '/new'
      fullPath: '/admin/books/$id/chapters/new'
      preLoaderRoute: typeof AdminBooksIdChaptersNewRouteImport
      parentRoute: typeof AdminBooksIdChaptersRoute
    }
    '/admin/books/$id/chapters/$chapterId/edit': {
      id: '/admin/books/$id/chapters/$chapterId/edit'
      path: '/$chapterId/edit'
      fullPath: '/admin/books/$id/chapters/$chapterId/edit'
      preLoaderRoute: typeof AdminBooksIdChaptersChapterIdEditRouteImport
      parentRoute: typeof AdminBooksIdChaptersRoute
    }
  }
}

interface AdminBooksIdChaptersRouteChildren {
  AdminBooksIdChaptersNewRoute: typeof AdminBooksIdChaptersNewRoute
  AdminBooksIdChaptersChapterIdEditRoute: typeof AdminBooksIdChaptersChapterIdEditRoute
}

const AdminBooksIdChaptersRouteChildren: AdminBooksIdChaptersRouteChildren = {
  AdminBooksIdChaptersNewRoute: AdminBooksIdChaptersNewRoute,
  AdminBooksIdChaptersChapterIdEditRoute:
    AdminBooksIdChaptersChapterIdEditRoute,
}

const AdminBooksIdChaptersRouteWithChildren =
  AdminBooksIdChaptersRoute._addFileChildren(AdminBooksIdChaptersRouteChildren)

interface AdminBooksIdRouteChildren {
  AdminBooksIdChaptersRoute: typeof AdminBooksIdChaptersRouteWithChildren
}

const AdminBooksIdRouteChildren: AdminBooksIdRouteChildren = {
  AdminBooksIdChaptersRoute: AdminBooksIdChaptersRouteWithChildren,
}

const AdminBooksIdRouteWithChildren = AdminBooksIdRoute._addFileChildren(
  AdminBooksIdRouteChildren,
)

interface AdminBooksRouteChildren {
  AdminBooksIdRoute: typeof AdminBooksIdRouteWithChildren
  AdminBooksCreateRoute: typeof AdminBooksCreateRoute
}

const AdminBooksRouteChildren: AdminBooksRouteChildren = {
  AdminBooksIdRoute: AdminBooksIdRouteWithChildren,
  AdminBooksCreateRoute: AdminBooksCreateRoute,
}

const AdminBooksRouteWithChildren = AdminBooksRoute._addFileChildren(
  AdminBooksRouteChildren,
)

interface AdminEventsIdRouteChildren {
  AdminEventsIdRegistrationsRoute: typeof AdminEventsIdRegistrationsRoute
}

const AdminEventsIdRouteChildren: AdminEventsIdRouteChildren = {
  AdminEventsIdRegistrationsRoute: AdminEventsIdRegistrationsRoute,
}

const AdminEventsIdRouteWithChildren = AdminEventsIdRoute._addFileChildren(
  AdminEventsIdRouteChildren,
)

interface AdminEventsRouteChildren {
  AdminEventsIdRoute: typeof AdminEventsIdRouteWithChildren
  AdminEventsCreateRoute: typeof AdminEventsCreateRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsIdRoute: AdminEventsIdRouteWithChildren,
  AdminEventsCreateRoute: AdminEventsCreateRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminNewsletterIdRouteChildren {
  AdminNewsletterIdEditRoute: typeof AdminNewsletterIdEditRoute
  AdminNewsletterIdPreviewRoute: typeof AdminNewsletterIdPreviewRoute
}

const AdminNewsletterIdRouteChildren: AdminNewsletterIdRouteChildren = {
  AdminNewsletterIdEditRoute: AdminNewsletterIdEditRoute,
  AdminNewsletterIdPreviewRoute: AdminNewsletterIdPreviewRoute,
}

const AdminNewsletterIdRouteWithChildren =
  AdminNewsletterIdRoute._addFileChildren(AdminNewsletterIdRouteChildren)

interface AdminNewsletterRouteChildren {
  AdminNewsletterIdRoute: typeof AdminNewsletterIdRouteWithChildren
  AdminNewsletterNewRoute: typeof AdminNewsletterNewRoute
  AdminNewsletterIndexRoute: typeof AdminNewsletterIndexRoute
}

const AdminNewsletterRouteChildren: AdminNewsletterRouteChildren = {
  AdminNewsletterIdRoute: AdminNewsletterIdRouteWithChildren,
  AdminNewsletterNewRoute: AdminNewsletterNewRoute,
  AdminNewsletterIndexRoute: AdminNewsletterIndexRoute,
}

const AdminNewsletterRouteWithChildren = AdminNewsletterRoute._addFileChildren(
  AdminNewsletterRouteChildren,
)

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewsletterRoute: typeof AdminNewsletterRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionRoute: typeof AdminSubscriptionRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRouteWithChildren,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewsletterRoute: AdminNewsletterRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionRoute: AdminSubscriptionRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifyRoute: AdminVerifyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsIdRouteChildren {
  EventsIdSuccessRoute: typeof EventsIdSuccessRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdSuccessRoute: EventsIdSuccessRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRouteWithChildren
  EventsCancelTokenRoute: typeof EventsCancelTokenRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRouteWithChildren,
  EventsCancelTokenRoute: EventsCancelTokenRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MembershipRouteChildren {
  MembershipSuccessRoute: typeof MembershipSuccessRoute
}

const MembershipRouteChildren: MembershipRouteChildren = {
  MembershipSuccessRoute: MembershipSuccessRoute,
}

const MembershipRouteWithChildren = MembershipRoute._addFileChildren(
  MembershipRouteChildren,
)

interface BooksSlugRouteChildren {
  BooksSlugChapterSlugRoute: typeof BooksSlugChapterSlugRoute
  BooksSlugIndexRoute: typeof BooksSlugIndexRoute
}

const BooksSlugRouteChildren: BooksSlugRouteChildren = {
  BooksSlugChapterSlugRoute: BooksSlugChapterSlugRoute,
  BooksSlugIndexRoute: BooksSlugIndexRoute,
}

const BooksSlugRouteWithChildren = BooksSlugRoute._addFileChildren(
  BooksSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRouteWithChildren,
  MemoirRoute: MemoirRoute,
  PodcastRoute: PodcastRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  BooksSlugRoute: BooksSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
